name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"
workers_dev = false

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "bodanetworks.us.kg"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
 routes = [
     { pattern = "docker.m.bodanetworks.us.kg", custom_domain = true },
     { pattern = "ghcr.m.bodanetworks.us.kg", custom_domain = true },
     { pattern = "quay.m.bodanetworks.us.kg", custom_domain = true },
     { pattern = "gcr.m.bodanetworks.us.kg", custom_domain = true },
     { pattern = "k8s-gcr.m.bodanetworks.us.kg", custom_domain = true },
     { pattern = "k8s.m.bodanetworks.us.kg", custom_domain = true },
     { pattern = "cloudsmith.m.bodanetworks.us.kg", custom_domain = true },
     { pattern = "ecr.m.bodanetworks.us.kg", custom_domain = true },
     { pattern = "docker.bodanetworks.us.kg", custom_domain = true },
     { pattern = "quay.bodanetworks.us.kg", custom_domain = true },
     { pattern = "gcr.bodanetworks.us.kg", custom_domain = true },
     { pattern = "k8s-gcr.bodanetworks.us.kg", custom_domain = true },
     { pattern = "k8s.bodanetworks.us.kg", custom_domain = true },
     { pattern = "ghcr.bodanetworks.us.kg", custom_domain = true },
     { pattern = "cloudsmith.bodanetworks.us.kg", custom_domain = true },
     { pattern = "ecr.bodanetworks.us.kg", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
